services:
  - type: web
    name: api-gateway
    env: docker
    dockerfilePath: ./api-gateway/Dockerfile
    healthCheckPath: /actuator/health
    healthCheckTimeout: 30
    autoDeploy: true
    environmentSlug: jar
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: EUREKA_ENABLED
        value: "false"
      - key: AUTH_SERVICE_URL
        value: ""
      - key: QUANTITY_SERVICE_URL
        value: ""
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false

  - type: web
    name: auth-service
    env: docker
    dockerfilePath: ./auth-service/Dockerfile
    healthCheckPath: /api/auth/ping
    healthCheckTimeout: 30
    autoDeploy: true
    environmentSlug: jar
    envVars:
      - key: PORT
        value: 8081
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: EUREKA_ENABLED
        value: "false"
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false

  - type: web
    name: quantity-service
    env: docker
    dockerfilePath: ./quantity-service/Dockerfile
    healthCheckPath: /api/quantity/actuator/health
    healthCheckTimeout: 30
    autoDeploy: true
    environmentSlug: jar
    envVars:
      - key: PORT
        value: 8082
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: EUREKA_ENABLED
        value: "false"
